[package]
name = "bitgrin_wallet"
version = "2.0.3"
authors = ["Bitgrin Developers <bitgrin@protonmail.com>"]
description = "Simple, private and scalable cryptocurrency implementation based on the MimbleWimble chain format."
license = "Apache-2.0"
repository = "https://github.com/bitgrin/bitgrin-wallet"
keywords = [ "crypto", "bitgrin", "mimblewimble" ]
readme = "README.md"
exclude = ["**/*.bitgrin", "**/*.bitgrin2"]
build = "src/build/build.rs"
edition = "2018"

[[bin]]
name = "bitgrin-wallet"
path = "src/bin/bitgrin-wallet.rs"

[workspace]
members = ["api", "config", "controller", "impls", "libwallet", "util"]
exclude = ["integration"]

[dependencies]
clap = { version = "2.31", features = ["yaml"] }
rpassword = "2.0.0"
ctrlc = { version = "3.1", features = ["termination"] }
failure = "0.1"
failure_derive = "0.1"
prettytable-rs = "0.7"
log = "0.4"
linefeed = "0.5"
semver = "0.9"

bitgrin_wallet_api = { path = "./api", version = "2.0.0" }
bitgrin_wallet_impls = { path = "./impls", version = "2.0.0" }
bitgrin_wallet_libwallet = { path = "./libwallet", version = "2.0.0" }
bitgrin_wallet_controller = { path = "./controller", version = "2.0.0" }
bitgrin_wallet_config = { path = "./config", version = "2.0.0" }

bitgrin_wallet_util = { path = "./util", version = "2.0.0" }

[build-dependencies]
built = "0.3"
